### ISSUE TITLE
Protected Land Ideas

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#16]
Xenu stated that protected lands are basically breaking the server due to their storage purposes and invulnerability to everything.

Instead of chucking them out the door, we could make it so that chests are not allowed, or limit chests somehow.

**Comment by Kladdkaka** [comment]
http://www.spigotmc.org/resources/plotsquared.1177/ Something like this in another world? You can block placement and stuff of blocks, we could block chests and stuff :)

**Comment by Joannou1** [comment]
The fact that that plugin exists is great...
We REALLY needed to move away from using WG to manage plots.
Very tedious and time consuming for those who had to mess with them.

**Comment by Cbjax** [comment]
How would we stop people storing stuff by building there stuff house of say gold and then replacing it with wood when they need the gold? I have a suggestion that would fix this problem. Why don't you have it so that you build a house in a creative world and then staff will transfer it to GLD. You can live in the house but you can't edit it once its in GLD. Also you could make stuff like you're only allowed 2 chests in the house or something like that. As long as we don't let them have 2 many chests I think giving them a few would be fine.

**Comment by Joannou1** [comment]
That sounds even more tedious...
I think the plot plugin allows you to blacklist certain blocks, and if not it can easily be done with WG.
As long as items can't be stored it should be fine.

**Comment by Kladdkaka** [comment]
It's not a good idea to transfer over stuff... People well just transfer over a double of opples

**Comment by Joannou1** [comment]
all seems to be working good!
added and set up.
