### ISSUE TITLE
Removal of lwc

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#17]
To make everyone have a fair chance, and everyone be able to get raids and stuff, we would need to remove lwc as it's breaking the server atm (like with prot lands). But we should think of some other type of protection, maybe if we could make so you can give chests higher resistance against tnt?

**Comment by Joannou1** [comment]
I think removing LWC is not a great idea to be honest..
To even it out, perhaps give defaults 1-3 chests, and 1-2 chests extra per rank up.

**Comment by Kladdkaka** [comment]
I think we might need to limit what you can have in those chests, like no enchanted gear and diamonds, but like building stuff, so if you get raided you can easily rebuild. Otherwise there will be no raids at all :l

**Comment by Joannou1** [comment]
Hm yeah, if there's a plugin that could do that that would be nice.
We want to encourage base building/foritifcation/raiding events more, and that would not help..
But at the same time, how much can you really cram into 2-6 chests?

Imagine if I told you that you had to move over all of your most valuable stuff into those 2-6 chests..
..there would still probably be a lot of good stuff in unprotected chests.

**Comment by Kladdkaka** [comment]
You could easily storage all your ores, enchanted gear, unless you're very rich. Of course there will be good stuff as obsidian, wood and stuff in the non-protected chests, but most people want ores and enchanted gear :l

**Comment by Joannou1** [comment]
Well in that case, it would probably be just one chest for all players, with no upgradability.
But again, could get rid of it.. up to players I suppose.

I wonder if there actually is another chest protection plugin with blacklisting abilities...
will have to check.

**Comment by Kladdkaka** [comment]
:+1:

**Comment by Joannou1** [comment]
We have decided that the best option is to remove LWC, but as a replacement, enable ender chests but limit it to one row at a time, allowing for upgradability later via ranks, etc.

Next step, find a plugin that can do this!
If not, get it made!

Set towny config to disallow others access to your chests so that your stuff is private.

**Comment by Kerrus** [comment]
There's a couple plugins (or used to be) that redirects the ender chest interact to point at a virtual inventory. That'd be functionally what you're looking to do. 

I agree about limiting what can be placed in chests- which should be more doable if you're actually using virtual inventory. Maybe limit it to weapons/armor/tools? But not money (emeralds). No stacking of non stackable items either.

**Comment by Joannou1** [comment]
Well money could be storable depending on how the initial economy is going to be..
Because a stack of emerald blocks is basically L$576, which may or may not be worth a lot.
And if we're limiting it to rows at a time, it would eat up a lot of your storage space.

Either way, I'll try to find and configure a plugin that will allow this to happen.
(Cause I think whatever plugin will need to intercept your interaction with the EC like you said, if you want to control what you can do with it)

**Comment by Joannou1** [comment]
All set up!
Perms assigned to respective ranks.
1 extra row per rank.

Plugin physically modifies your enderchest space from the block and command if you have the perm.

Limiting the contents probably won't be necessary, as people will fill it up quick with emerald blocks / valuable armor.. and will still have to put other valuables elsewhere.

**Comment by Kerrus** [comment]
Looks good.
