### ISSUE TITLE
McMMO Rebalancing

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#22]
Well I think we almost missed the elephant in the room...
Can't have noobs and people getting 1 shotted by those who have 800 in axes now can we?

We either need to redefine the maximum level, or their effectiveness, or both.
McMMO is very configurable for every skill, so setting the XP curve to be high for that and lowering its PVP effectiveness may be for the best.

Again, up for debate and discussion on not just Axes, but any other skills that are considered OP.

**Comment by Kladdkaka** [comment]
I think all combat skills should be completely removed, except for a nerfed archery. However I think we should add some other type of pvp abilities that you can use. Think of like a staff you can use magical spells with, like to freeze players, throw players away from you, slow them down, make them blind. Like with the magic plugin we had for a day. I think that could be way more balanced than mcmmo.

Just my opinion though :P

**Comment by Joannou1** [comment]
That would work out really well actually.
And instead of removing the combat skills completely, if possible give them a MAX of 5-10% increase in damage at the highest level. (Or just make the highest level 100 or something and have it do 5% extra damage.. So that way it still feels like you are earning some sort of skill advantage from all that hard work, but at the same time not being overpowered for everyone.

**Comment by Kladdkaka** [comment]
Yup that sounds completely fair :)

**Comment by Kerrus** [comment]
What you might do is that MCMMO has a whole crapload of subskills that currently people get almost immediately. If instead we gate those by their level in the skill, and nerf the effect percentage for damage affecting skills, it gives people stuff to work towards. 

I mean the basic stuff doesn't have to unlock at zero, that's just something we have as a default setting.

**Comment by Joannou1** [comment]
I think what we've mostly agreed on is to disable most of those abilities for PVP and have them still work against mobs and whatnot.

But if we could make it so that certain abilities can only do so much then it may be possible.

**Comment by Kerrus** [comment]
Oh the config for mcmmo is infinitely customizable for damage/quality of all those abilities. The main problem existing/old GLD has had is that we 'had' to grandfather in all that shit. Remember when we moved axes up to veteran and the shitstorm it started? 

If we were just starting fresh we could re-do the entire config, balance shit out, make it so that the extra abilities are there but are minor, and look into setting it up so they don't all unlock right away. 

I think there's some settings in there to make them only work against mobs, but honestly one of the big draws of GLD was that it had the enhanced pvp. I think it's just a matter of flattening out that power tree so that you have more lateral options and less depth of powerups. If we increase the amount of points it takes to get to levels, decrease the earn rate, stop selling mcmmo points on the website, and then flatten the amount of boost higher levels have....

Then it shifts the whole dynamic, because you're still rewarded for leveling up, but those rewards aren't so strong that you'll have an unstoppable advantage over a new player. Someone with 1200 axes under such a system would only be about as strong as someone with, say, 300 axes under the old system. But they'd have access to more abilities than that hypothetical 300 axes players (You can even do shit like fractional armor damage if you really want to. 

I think it'd definitely be something to fiddle around with and find the right balance.

**Comment by Joannou1** [comment]
See the new post, #52 for a much more clear and laid out idea of how McMMO stuff will be done.
