### ISSUE TITLE
Sethome Debacle

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#24]
Kerrus:

Oh, that reminds me. The new system I don't think we should have or sell as donor rank benefits: sethomes
I think people should have one sethome
and then use warps for everything else
maybe get a warps plugin so people can set up town warps
but without gads of sethomes a lot of the policing stops being an issue
and players have reason to travel and shit

Well I mean like a town can set a warp that works for any member of the town. If you got a warps plugin to mod you could even hook it into towny/factions/citizens whatever so it respects the 100 block rule, and do shit like have it cost money and expire
[1:17:18 AM] Kerrus Magrus: encourages player cooperation and shit, helps for wartime, less commands for players to learn (once they  know how it works), and you don't get shit like people constantly setting home in various towns. Gotta actually warp, alliances actually mean something
[1:17:36 AM] Kerrus Magrus: I dunno if you remember, but on the old server RW and I once built a really really really long town
[1:17:45 AM] Kerrus Magrus: it was one plut wide, and like 300 plots long
[1:17:49 AM] Kerrus Magrus: and had warps every 10 pluts
[1:17:51 AM] Kerrus Magrus: plots*
[1:17:56 AM] Kerrus Magrus: err, towny teleports
[1:18:03 AM] Kerrus Magrus: and they charged money for people to use
[1:18:10 AM] Kerrus Magrus: it was awesome. Didn't last long, but it was awesome
[1:18:24 AM] Kerrus Magrus: something like that would be great if it could be set up so it's automatic to players
[1:18:59 AM] Kerrus Magrus: you could do that and basically there'd be a reason for players to set up public towns to be war raiding waypoints and shit
## 

---
## 

This is a really cool idea.
I didn't know you even could set up town warps, can you?
or er.. teleports?
Conflicting information!

**Comment by Kerrus** [comment]
It involved the outpost mechanic. You can make your town public and set a fee for people to use /t spawn to spawn in, with the money paid to the town bank. You can also set a spawn to the outpost number IIRC so people can spawn to your outposts. 

I know there's talk about moving away from towny- I'm okay with that, but in general I definitely still feel what I said in here is accurate- sethomes have been problematic for as long as we've had them, and I think we really need to encourage interactivity between players and towns/factions/whatever.

Also: It's Debacle. 

Also also: Not sure where to put this, but I was thinking that if we do do a sethome for donor ranks, that it should only be one sethome that they can set via command, and then possibly give them a limited number of single use/re-usable spawns.

So a player goes '/set spawn' or the like at a location in the desert. Then the next time they hit '/spawn' or whatever the command is, they appear at that spawn, and the spawn deletes itself/applies a 1 hour cooldown before it can be placed again. 

This would still let some of the familiar behaviour occur, but it would also limit the set home town raiding mechanic, since players would only be able to go there once, esp if we set a radius limit or the like.

**Comment by Joannou1** [comment]
Ah the outpost mechanic sounds really cool if the fee could go towards the town and not the main server account.

People have said we should move away from Towny, but we just couldn't do that.. 
It would be sacreligious basically lol.

Damn you Chrome! For some reason it didn't say it was wrong in the title area.

## 

The temp spawn idea is quite good, it could work in conjunction/simultaneously with a single sethome that has a cooldown period of a day or so.

Chip is looking for challenging plugins to make, so maybe I can point him here :p

**Comment by Joannou1** [comment]
Gona close this now, the magnificent chip has done us a solid and made the tempspawn plugin.
Fully equipt with mysql support, perm nodes for custom cooldowns, and various commands.

./tempspawn set - Set your temporary spawn
./tempspawn spawn - Spawn at your temporary spawn

Upon death you respawn at the tempspawn, tempspawn is then deleted and you must wait the cooldown period to reset it.

tempspawn.cooldown.[numberofminutes]
