### ISSUE TITLE
Donator Rank Names

### ISSUE THREAD

**Issue by Jeremy9600** [GLServers/GLD#40]
Sand Traveler

VIP ~ Sand Adventurer

Premium

Exiled

Captain

Veteran

1337

Desert Sage

Dark King ~ Desert King

Dark Lord ~ Desert Lord

Risen Titan ~ Pharaoh

**Comment by Joannou1** [comment]
All good suggestions, still open to more ideas though!

**Comment by Kerrus** [comment]
I'll just append my list to this. 

I'll also note that I think that a lot of the GLD rank names are a little outdated, and could do with, A, pruning, and B, changing their names. 

Wanderer - Basic Rank <-- Start as this rank
Skilled Wanderer - Advanced Rank (15$ for three months)

Mercenary - Basic Rank (5000 igc)
Mercenary Commander - Advanced Rank (25$ for 3 months)

Hunter - Basic Rank (10,000 igc)
Hunt-Team Leader - Advanced Rank (35$ for 3 months)

Nomad - Basic Rank (20,000 igc)
Nomad Captain - Advanced Rank (45$ for 3 months)

Mystic - Basic Rank (40,000 igc)
Legendary Mystic - Advanced Rank (55$ for 3 months)

**Comment by Joannou1** [comment]
I quite like these rank names.
I wonder if we can still re-use one GLD rank name for fun though?
(ST or something maybe)

**Comment by Kerrus** [comment]
Maybe drop hunter/hunt-leader, bump nomad down to its rank, and then insert Desert Sage/Dark King as a normal/premium rank, with the capstone being mystic/legendary mystic. 

Maybe some other changes, and make it so that the advanced ranks are more in line with the old ranks, but with new flavour to tie it together. So something a little like this:

Normal Rank // Paid Rank

Wanderer // Adventurer

Mercenary // Commander

Nomad // Captain

Desert Sage // Dark King

Ancient Sage // Legendary Mystic

**Comment by Cbjax** [comment]
I like the names but instead of Commander can we use Pokey? If you don't know what a Pokey is then take a look http://prntscr.com/7akuno I think most people will know what it is once they see the pic.

**Comment by Kerrus** [comment]
random mario reference? eh, not a huge fan sorry.

**Comment by Joannou1** [comment]
yeah same, a little bit niche/odd

**Comment by Joannou1** [comment]
Seems like the rank names are fairly solid at this point.
They've been setup in game and look quite good.

Thanks Kerrus for the names and setting them up!
