### ISSUE TITLE
Fly Abuse fixes

### ISSUE THREAD

**Issue by ghost** [GLServers/GLD#41]
Fixing these things programmatically rather than extreme enforcement

iv: Minion TPing. Now this one is a little tricky, Minion TPing is when people TPA to you, or you TPAhere, with the express purpose of helping you in a 
fight. Now, this is more geared at when people are flying, and they TP people in while they’re safe and sound. Because honestly, if you can get someone in to 
help you on foot, you deserve it.
Fix: Make fly be accessible at the same rank as god and have them be invincivle when in fly.

i: No Fly/Vg/Disguise Scooping. Donors, you have various perks, but these perks are also viable to be abused. 
Do not have Fly/VG/Mob Disguise active and run over a bunch of items and storm off with them. You can do this and run away on foot, out of good and as a
person; but otherwise just stop.
Fix: Disable player death drops being picked up when 1. using these perks or 2. within 60 seconds of exiting these perks

YOU MAY NOT: Fly over a town's walls.  
Fix: Disable flying in enemy towns    

no raiding in vanish/fly/mob disguise  
Fix: Disable placing of creeper spawn eggs, lava, and fire while in fly.

YOU MAY NOT: Fly over a town's walls.  
Fix: Didn't I just say this?

YOU MAY NOT: Use Fly to light towns on fire.  
Fix: Look above   

YOU MAY NOT: Use Fly to plant creeper eggs or detonate creepers, especially in otherwise hard to reach places.  
Fix: look above

Feel free to leave comments on changes

**Comment by Kerrus** [comment]
From a programming perspective, it may be possible to add listeners to the fly plugin we use/make so that it disallows people teleporting to you, pickup of items, pvp, potion use, whatever while in fly, and also turns off and can't be turned on when you enter a town that isn't your own town. 

Might piss some people off, but it'd solve like 90% of those issues. 

Bonus points if we make it use spectator mode so they can't interact with the world at all. That'd mean they could fly through walls and shit, I suppose, but I think that might be a better solution than trying to eliminate all the normal loopholes.

**Comment by TyJcksn** [comment]
Issue with spectator is that it's just like free can and X-ray combined. Sure it doesn't show ores but it still does quite a bit more.

**Comment by Joannou1** [comment]
I feel like we should do as Kerrus said in #50 and try to find another method, as fly should not be a perk for many reasons.
