### ISSUE TITLE
Noob Treatment

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#44]
Making a new post in place of #38.

We need to get a PVP timer plugin that actually works well to get noobs started off right.
First impressions are everything, and getting murdered quickly is not a good one.

(Initially disable pvp for 10-30 mins with an override command.)

Open for discussion on if this should be done, or if anything different should be done.

**Comment by Cbjax** [comment]
If PVP is disabled for 30 mins then people would be able to raid with out getting killed. Some people may even get alts on during war to raid towns. Also say if the are new noob wants to PVP in the PVP area and can't because its off. He might not wait the 30 mins. Also he could go in the PVP area and pick up the drops of big donors when they die. Unless there are fixes for problems like this I don't think this should be a thing.

**Comment by Joannou1** [comment]
Yeah, probably not the best idea then.
There has been discussion on how we should handle first spawns though.
(No spawns, rule spawns then RP, other spawns, etc)

**Comment by Jeremy9600** [comment]
We could at least have announcements saying something like

"It is recommended that new players do /rp instead of crossing into border!" or something. Dunno.

**Comment by Joannou1** [comment]
If there is a main border area like on GLD now, the warnings need to be much more in-your-face and obvious.. so that they know what they are risking by running out there blindly.

I think the current idea is to have the main spawn in the middle of the map to allow for more exploration and less of a choke-point like the current spawn.

**Comment by Kerrus** [comment]
I actually have an idea- it'd need some automation, but should in theory be easier than not.

Make a noob town and automate it. So rather than just going out and exploring, after the tutorial noobs are put into a noob town, given a plot, and teleported to the their plot, where it sets their home to the plot and shit, so they can learn how to contribute to the town, mine, explore, whatever, from a position of safety. But after a month or whatever, start charging them 'rent' (with messages/mail/whatever) and have the rent payments be higher than if they were in a normal town, to encourage them to head out and start their own towns.

Or just outright kick them out after a month- possibly with some sort of plugin setup to just transplant their entire plot out into the desert or something. 

Thoughts?

**Comment by Kladdkaka** [comment]
"If PVP is disabled for 30 mins then people would be able to raid with out getting killed. Some people may even get alts on during war to raid towns."

We can disable picking up items

"Also say if the are new noob wants to PVP in the PVP area and can't because its off. He might not wait the 30 mins."

New players shouldn't pvp, they don't have items

"Also he could go in the PVP area and pick up the drops of big donors when they die."

We can disable picking up items
@Cbjax

**Comment by Kladdkaka** [comment]
I think we really need to move away from the idea about making it super super easy for noobs. The players we need is players that have played on servers before, not any 9 year old who just got the game.

What we need is to show them the selling point fast.

For example, if I would be a faction player (faction is biggest gamemode atm) and I would go on gld the first time, I would see it's a towny server, and I would assume it's a PvE server and just leave.

We need to show them about the server fast, so they know about how the server works, and also teach them how to survive, not like giving them protection for a month. More like, 

"first you should go to a random place in the desert by doing /rp (which stands for random teleport), then you should dig down and find a cave, you should go get some resources, then you should go to the ground, go to the nearest mountain and make a base, now you will need to make a town, to make a town you need to buy one, to get currency to buy with, you need to place down a chest and type [Vault] and place emeralds in it, then you do /t new. yada yada yada."

And make it all under 5 minutes, because peoples attention span isn't much bigger than that

**Comment by Kladdkaka** [comment]
With something like this, http://dev.bukkit.org/bukkit-plugins/servertutorial/
For a example go on mineplex and do the tutorial :p

**Comment by Kerrus** [comment]
giving them a textwall is not going to look good or help out. That's why I support the idea of a automatic noob town. 

What might be possible is some sort of quest plugin setup, where they get a quest line that basically does the server tutorial for them in a simple and easy to understand manner. Players can choose to skip the quests by taking an in-chat test , but if they work to complete them they get little extra rewards and shit. 

At the end of the quest line, or if you skip them, you get kicked out of the noob town (with your stuff) and can go exploring, make your own towns, whatever.

With such a setup, it would be very easy to indicate that GLD is a pvp oriented server and griefing is legal and so on and so forth.

But idk how difficult it would be to set up a quest plugin- I know they exist but not much beyond that.

**Comment by Joannou1** [comment]
Most noob stuff has been kinda figured out..
I think this issue has served its purpose.

-Seperate spawn just for first time noobs.. done.
-A quick visual informational area in said spawn... done.
-First impression isn't getting killed in pvp.. done.

For any more suggestions on what to do with noobs, we should probably open a seperate post for it to keep better track.

See #28 and #47 (rule book / quests)

We do need to figure out a noob kit, but we'll figure that out later.
