### ISSUE TITLE
Normal and Donor Rank feature discussion and suggestions.

### ISSUE THREAD

**Issue by Kerrus** [GLServers/GLD#53]
Rank Benefits for normal/donor ranks

Normal ranks:

Basic kits 'Wanderer' 'Mercenary' 'Nomad' 'Sage'
Cooldown reduction for the spawn plugin
access to a single sethome via command (after first rank)
Cooldown reduction for rejoining Nexus world.
Chimera Wing (blocked in pvp).
Summon Horse (faster/more stamina at each level).

Paid Ranks:

Advanced kits (more items, not necessary better items) 'Adventurer' 'Commander' 'Captain' 'King'
set multiple tempspawns?
greater cooldown reduction. 
Ability to vote for next Nexus World features? (so like collate donor votes, feed that into the worldgen after we start making more custom worlds).
Summon horse that's slightly faster than the horse the normal rank gets at each rank/has better jump distance. 
MCMMO endurance perk (none of the lucky perk, it's too OP).
Protected area (no item storage, no placement of emerald stuff). Possibly in another donor only world, idk. Basically just a build protected shit place, though with a block placement blacklist to prevent abuse. 

Alternatively access to a Creative server? Or something like that. 

Special Feature for donors: 

DESIGN AN APOCALYPSE BOSS. Gain access to a special section on the forums where you can post to contribute to the design of a boss mob that shows up during the apocalypse event in the Nexus World! Name it and help choose features!

**Comment by Joannou1** [comment]
I think all of these are pretty good.
I especially like the ability to vote for the nexus world features and or theme.

Only thing I have to figure out is how to automate in-game ranks to vBulletin groups, I think we need that for sanity's sake as well

**Comment by Kladdkaka** [comment]
http://www.spigotmc.org/resources/communitybridge.2232/

**Comment by SirCreep** [comment]
Hello everyone. After accidentally posting on the outdated page, here is my thoughts on the ranks: A donor perk I would like to see is the disguiser kit that exiled and up currently has access too, but maybe open it to more animal selections and lower it down? It doesn't really serve a purpose, just seems like something fun to do. The exiled rank currently just has the spider and the pig, which is minuscule compared to the number of mobs in the game and available with the disguiser plugin. Anyways, that is my one thing I would like to see added in. I do think that there should be less paid ranks, somewhere between 4-7, and maybe decreasing the price of ranks, especially with the notion that they aren't going to offer as much as they used too. With that, I think that the paid ranks should get better items than the non-paying people, but not items that aren't achievable to f2ps. Like multiple enchant items which could take a while to make normally in a kit, like the Pvp kit currently. To clarify, while the donation perks should be a bit more balanced, there should be some clear sort of difference between donor and non donor. Personally, I donated to help this server, but also because I really wanted the fly perk and other bonuses. Having reduced cool times isn't going to attract as many people to donate as the current perks because it isn't tangible; you cant really touch the reduction, its just there. I do really like that voting feature, that provides donors more interactions with the server and makes their donation feel more valued. Anyways, that's how I feel about ranks and the direction they are headed. Oh one more thing on the names of the ranks, I feel like using the rank names we already have would work. Designate certain rank names, like S-T, exiled, veteran, and desert sage, as the ranks you get in game without donating. Then use some of the remaining ranks for the new donor levels. Other than that it sounds good. If I have any more ideas I will post them

**Comment by Kerrus** [comment]
holy formatting batman. 

Anyways we appreciate your comments, but I'll make a note here that basically we're going from the current rank system to a system where there are essentially only five ranks, so benefits will be less strung out between them. Name wise, we'll be adopting more themed names but keeping some of the iconic GLD names. 

We're also absolutely keeping an eye out for stuff to entice future donors, we do want our ranks to be great- but at the same time we're cutting back on benefits that, like fly- while it may be common to servers and thus 'expected'- also actually hurts the play experience and causes issues overall in the context of being a benefit for GLD donors.

We are going to look into the possibility of flying _mounts_, but I can't make any promises.

**Comment by Joannou1** [comment]
1 extra ender chest row per rank.

Longer perk activation time:
mcmmo.perks.activationtime.eightsecondsperks
mcmmo.perks.activationtime.fourseconds
mcmmo.perks.activationtime.twelveseconds

Maybe passive xp boost that is seperate from entire server xp boost (50/150%?)
mcmmo.perks.xp.10percentboost

**Comment by Joannou1** [comment]
Main perks have been done for a bit, feel free to open new ones for suggested perks or something.
