### ISSUE TITLE
/Chronicle: Lore tracker plugin [plugin request]

### ISSUE THREAD

**Issue by Kerrus** [GLServers/GLD#58]
/Chronicle 

Feature that lets players keep track of all the lore they've uncovered about the history of the world and its secrets. Works like a book that gradually fills up with subdirectories for the various books players can find. Will tell you which books you're missing.

(Looks like a book with an inventory screen inside maybe? Or just a book that when used opens an inventory screen that holds the books you've found, with spaces for the books you don't have. Or maybe even non-enchanted/labeled books with just their number to indicate the ones you need to find)

Possibly also equipped with some sort of compass that points in the direction of the nearest book to help players navigate to ruins on the nexus world, and other tools, like an apocalypse countdown and gravity falls references. 

Tied into achievements for unlocking books and piecing together the narrative. 

I figure the narrative would be in a combination of books, and item lore- so like swords with lore about legendary heroes, towns, whatever.

**Comment by Joannou1** [comment]
I've decided to try to code this myself.
So far so good, got all the core stuff set up.

It'll be a double chest that opens up with all the lore entries lined up in a set order.
Each entry will be a written book that glows, or a standard unwritten book.

![666b7](https://cloud.githubusercontent.com/assets/997747/7901924/05366f0c-0756-11e5-9851-6a07d0860716.png)

![a497b](https://cloud.githubusercontent.com/assets/997747/7901925/0ba65b9a-0756-11e5-877e-d2306cc5a8a4.png)

Database stuff, commands, chest layout/item formatting, all done
Added an admin list command and a command to add the book in your hand to the entries.
~~-need to install a listener for when you pick up an item (written book) and the title exactly matches with one in the db, then add it to your available lore bits.~~
-have a filter thing to only show the entries you have,
-prevent books from being taken out of menu
-on book click, load the entry

**Comment by Kerrus** [comment]
That looks amazing.

**Comment by Joannou1** [comment]
Plugin is completely done!

Everything that I can think of has been completed and tested fairly well.

-Completed all inputs/outputs/safety measures.
-Permission nodes setup and assigned.
-New commands work quite well.
-Stuff.. more stuff.. everything.. my everything hurts
-Dupe prevention
-SQL fixes and stuff 
-did I mention stuff?

Commands:
/ladmin to view all subcommands..
you may type in each subcommand and their arguments to see what it takes.

'Unlock books' will be generated into the nexus world.
To manually give/place unlock books, they can be retrieved from the '/ladmin view all' command.
To add a new book, write one, and with it in you hand type /ladmin add
To edit a book, do /ladmin list to get the id of what you want to edit, then do /ladmin edit [argument] |id|
(you can edit the content, order, title, lore and author)

To view another players current lore set, type /ladmin view [player]

All discoveries of lore are logged in the database.. (location, time, etc)

There's probably more, but most of it is self explanatory with the command help :)

If there are any more issues, post them here or in a seperate post.. 
I'll close it because this post's main purpose has been fulfilled!

For my first plugin, this contains about 2000 lines of code and quite some advanced stuff.
Pretty happy with the results!

![13a79](https://cloud.githubusercontent.com/assets/997747/7936060/f94dbdee-08ea-11e5-994b-a35ffed32c8c.png)

**Comment by MystHawk** [comment]
Maybe when you spawn, you get a bookshelf that is for the Chronicles, but it would be kinda hard to program because you would have to place and then right click to open it
